version: '3.4'
services:
  web:
    image: node:alpine
    container_name: tl_frontend
    entrypoint: /bin/sh
    ports:
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true